// content/ 配下の Markdown を SSR ワーカーから import できる TS モジュールへ事前コンパイルする。
// Cloudflare Workers にはファイルシステムがないため、marked / gray-matter は
// ここ（ビルド時・Node 上）でのみ使い、ランタイムには生成済みデータだけを渡す。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { marked } from 'marked';
import { sanitizeContentHtml } from './sanitize-content-html.mjs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outDir = path.join(root, 'src/generated');
const outFile = path.join(outDir, 'content.ts');

function readMarkdownDir(dir) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) return [];
  return fs
    .readdirSync(abs)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => {
      const slug = f.replace(/\.md$/, '');
      const raw = fs.readFileSync(path.join(abs, f), 'utf8');
      const { data, content } = matter(raw);
      return { ...data, slug, contentHtml: sanitizeContentHtml(marked.parse(content)) };
    });
}

// セッションごとの OGP 画像（public/sessions/<slug>.png）の有無もビルド時に確定させる。
function listSessionOgSlugs() {
  const dir = path.join(root, 'public/sessions');
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.png'))
    .sort()
    .map((f) => f.replace(/\.png$/, ''));
}

const blogPosts = readMarkdownDir('content/blog');
const sessionEntries = readMarkdownDir('content/sessions');
const sessionOgSlugs = listSessionOgSlugs();

const banner =
  '// AUTO-GENERATED by scripts/build-content.mjs — 手で編集しないでください。\n' +
  '// 元データ: content/blog/*.md, content/sessions/*.md, public/sessions/*.png\n';

const body =
  `export const blogPosts = ${JSON.stringify(blogPosts, null, 2)};\n\n` +
  `export const sessionEntries = ${JSON.stringify(sessionEntries, null, 2)};\n\n` +
  `export const sessionOgSlugs = ${JSON.stringify(sessionOgSlugs, null, 2)};\n`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, banner + body);
console.log(
  `generated ${path.relative(root, outFile)}: ` +
    `${blogPosts.length} blog posts, ${sessionEntries.length} sessions, ${sessionOgSlugs.length} og images`
);
